TrainingProje/Proje/ProjeMvc/Models/TrainingProgramDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjeMvc.Models
{
    public class TrainingProgramDetailViewModel
    {
        public int TrainingProgramDetailId { get; set; }

        public DateTime StartDate { get; set; }

        public DateTime EndDate { get; set; }

        public string Description { get; set; }

        public int? EducatorId { get; set; }

        public int? LessonId { get; set; }

        public int? TrainingProgramId { get; set; }

        public int? ClassId { get; set; }
    }
}

TrainingProje/Proje/ProjeMvc/Controllers/TrainingProgramController.cs
using Business.Abstract;
using DataAccess.Concrete.EntityFramework;
using Entities.Concrete;
using Entities.DTOs;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjeMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjeMvc.Controllers
{
    public class TrainingProgramController : Controller
    {
        private readonly ITrainingProgramService _trainingProgramService;

        private readonly IClassService _classService;

        public TrainingProgramController(ITrainingProgramService trainingProgramService)
        {
            _trainingProgramService = trainingProgramService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Add()
        {
            //trainingProgram.TrainingProgramId = 0;
            Proje2Context projeContext = new Proje2Context();


            return View();
        }

        [HttpPost]
        public ActionResult Add(TrainingProgramDto trainingProgramDto)
        {
            trainingProgramDto.TrainingProgramId = 0;
            trainingProgramDto.ClassId = 0;
            Proje2Context projeContext = new Proje2Context();
            List<Class> sınıflar1 = projeContext.Classes.Where(x => x.TrainingId == trainingProgramDto.TrainingId).ToList();
            TrainingProgram trainingProgram2 = projeContext.TrainingPrograms.Include(x => x.Training).Where(x => x.TrainingId == trainingProgramDto.TrainingId).FirstOrDefault();
            Training training3 = projeContext.Trainings.Where(x => x.TrainingId == trainingProgramDto.TrainingId).FirstOrDefault();
            Lesson lessons = projeContext.Lessons.Where(x => x.TrainingId == trainingProgramDto.TrainingId).FirstOrDefault();
            if (trainingProgramDto.Kota > 100)
            {
                return Json("17");
            }
            if (trainingProgramDto.Name == null)
            {
                return Json("7");
            }
            if (lessons == null)
            {
                return Json("11");
            }
            if (training3 == null)
            {
                return Json("10");
            }
            if (training3 != null)
            {
                if (DateTime.Now > training3.TrainingLastdate)
                {
                    return Json("5");
                }
            }

            Training training2 = projeContext.Trainings.Where(x => x.TrainingId == trainingProgramDto.TrainingId).FirstOrDefault();
            
            Lesson lesson1 = projeContext.Lessons.Include(x => x.Training).FirstOrDefault();
            List<Lesson> dersler = projeContext.Lessons.Where(x => x.TrainingId == trainingProgramDto.TrainingId).ToList();
            foreach (var d in dersler)
            {
                int s = 0;
                if (d != null)
                {
                    s++;
                }
                if (s == 0)
                {
                    return Json("6");
                }

            }
          
            TrainingProgram trainingProgram1 = new TrainingProgram();
            trainingProgram1.TrainingId = trainingProgramDto.TrainingId;
            trainingProgram1.Name = trainingProgramDto.Name;
            Training training = projeContext.Trainings.Where(x => x.TrainingId == trainingProgramDto.TrainingId).FirstOrDefault();
            List<Class> sınıflar = projeContext.Classes.Where(x => x.ClassName == trainingProgramDto.ClassName).ToList();
            if (trainingProgramDto.ClassName == null && trainingProgramDto.Kota != 0)
            {
                return Json("3");
            }
            

            foreach (var s in sınıflar)
            {
                TrainingProgram trainingProgram = projeContext.TrainingPrograms.Where(x => x.TrainingProgramId == s.TrainingProgramId).FirstOrDefault();
                if (trainingProgram != null)
                {

                    if (trainingProgram.Name == trainingProgramDto.Name)
                    {
                        return Json("2");
                    }
                    if (s.ClassName == trainingProgramDto.ClassName && s.TrainingId != trainingProgramDto.TrainingId)
                    {
                        return Json("2");
                    }
                }

            }
            projeContext.Add(trainingProgram1);
            int sonuc1 = projeContext.SaveChanges();
            Class sınıf = new Class();
            if (trainingProgramDto.ClassName == null)
            {

                sınıf.ClassName = trainingProgramDto.ClassName;
            }
            else
            {
                sınıf.ClassName = trainingProgramDto.ClassName;
            }
            sınıf.TrainingId = trainingProgramDto.TrainingId;
            sınıf.Kota = trainingProgramDto.Kota;
            sınıf.TrainingProgramId = trainingProgram1.TrainingProgramId;
            projeContext.Classes.Add(sınıf);
            int sonuc = projeContext.SaveChanges();
            return Json("200");
        }

        public ActionResult GetAll()
        {
            Proje2Context projeContext = new Proje2Context();
            //TrainingProgram trainingProgram = projeContext.TrainingPrograms.Include(x => x.Training).FirstOrDefault();
            List<TrainingProgram> trainingPrograms = projeContext.TrainingPrograms.Include(x => x.Training).Where(x => x.Name == 1).ToList();

            List<SelectListItem> lesson = (from i in projeContext.Trainings.Where(x => x.TrainingName != null).ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.TrainingName,
                                               Value = i.TrainingId.ToString()
                                           }).ToList();
            ViewBag.Lessons = lesson;
            List<Class> sınıflar = projeContext.Classes.ToList();
            List<Class> sınıflar1 = new List<Class>();
            foreach (var t in trainingPrograms)
            {
                foreach (var s in sınıflar)
                {
                    if (t.TrainingProgramId == s.TrainingProgramId)
                    {
                        sınıflar1.Add(s);
                    }
                }
            }
            List<Class> sınıflar3 = projeContext.Classes.Include(x => x.Training).ToList();
            List<Class> sınıflar2 = projeContext.Classes.Include(x => x.TrainingProgram).ToList();
            
            return View(sınıflar1);
        }


        public ActionResult GetAllS()
        {
            Proje2Context projeContext = new Proje2Context();
            List<TrainingProgram> trainingPrograms = projeContext.TrainingPrograms.Include(x => x.Training).Where(x => x.Name == 2).ToList();

            List<SelectListItem> lesson = (from i in projeContext.Trainings.Where(x => x.TrainingName != null).ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.TrainingName,
                                               Value = i.TrainingId.ToString()
                                           }).ToList();
            ViewBag.Lessons = lesson;
            List<Class> sınıflar = projeContext.Classes.ToList();
            List<Class> sınıflar3 = projeContext.Classes.Include(x => x.Training).ToList();
            List<Class> sınıflar2 = projeContext.Classes.Include(x => x.TrainingProgram).ToList();
            List<Class> sınıflar1 = new List<Class>();
            foreach (var t in trainingPrograms)
            {
                foreach (var s in sınıflar)
                {
                    if (t.TrainingProgramId == s.TrainingProgramId)
                    {
                        sınıflar1.Add(s);
                    }
                }
            }
            return View(sınıflar1);
        }
        [HttpGet]
        public ActionResult Update(int ClassId)
        {
            Proje2Context projeContext = new Proje2Context();
            Class sınıf = projeContext.Classes.Where(x => x.ClassId == ClassId).FirstOrDefault();
            TrainingProgram trainingProgram = projeContext.TrainingPrograms.Where(x => x.TrainingProgramId == sınıf.TrainingProgramId).FirstOrDefault();
            Training training = projeContext.Trainings.Where(x => x.TrainingId == trainingProgram.TrainingId).FirstOrDefault();
            ClassTrainingProgram güncelle = new ClassTrainingProgram();
            ViewBag.Name = trainingProgram.Name;
            güncelle.ClassName = sınıf.ClassName;
            güncelle.ClassId = sınıf.ClassId;
            güncelle.TrainingName = training.TrainingName;
            güncelle.Kota = sınıf.Kota;
            return View(sınıf);
        }

        [HttpPost]
        public ActionResult Update(ClassDto classDto)
        {

            Proje2Context projeContext = new Proje2Context();
            if(classDto.Name == 0)
            {
                return Json("1");
            }
            if (classDto.Kota > 100)
            {
                return Json("17");
            }
            List<Class> sınıflar = projeContext.Classes.Where(x => x.ClassName == classDto.ClassName).ToList();
            foreach (var s in sınıflar)
            {
                TrainingProgram trainingProgram1 = projeContext.TrainingPrograms.Where(x => x.TrainingProgramId == s.TrainingProgramId).FirstOrDefault();
                if(trainingProgram1.Name == classDto.Name)
                {
                    return Json("50");
                }
            }
            Training training1 = projeContext.Trainings.Where(x => x.TrainingId == classDto.TrainingId).FirstOrDefault();
            if (classDto.Kota > training1.kota)
            {

TrainingProje/Proje/ProjeMvc/Views/TrainingProgramDetail/Add.cshtml
@model Entities.DTOs.TrainingProgramDetailDto
@*@using Entities.DTOs

    @model Tuple<SiteDetailDto,SiteAddDetailDto>*@

@{
    ViewData["Title"] = "Eğitim Programı Ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<script src="~/js/site.js"></script>
<link href="~/jquery-ui-1.11.4/jquery-ui.min.bootstrap.css" rel="stylesheet" />
<h1>Eğitim Programı Ekle</h1>
<br />
<div class="content" style="width: 400px; margin-left: 35%; margin-bottom: 10%; margin-top:5%">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header"><h5 class="title">Eğitim Programı Ekle</h5></div>
            <div class="card-body">
                @using (Html.BeginForm("Add", "TrainingProgram", FormMethod.Post))
                {
                <div class="form-group">
                    @Html.Label("Eğitimin Adı:")<br />
                    @Html.DropDownListFor(x => x.LessonId, (List<SelectListItem>)ViewBag.Liste, "Seçiniz", new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.LessonId, "", new { @class = "text-danger" })
                    <br /><br />
                    @*@Html.Label("Eğitim günü seçiniz:")<br />
                    @Html.DropDownListFor(x => x.WhichDayName, (List<SelectListItem>)ViewBag.Day, "Seçiniz", new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.WhichDayName, "", new { @class = "text-danger" })*@
                    <br /><br />
                    @*@Html.Label("Eğitim günü seçiniz:")<br />
                    @Html.TextBoxFor(x => x.Hours, (List<SelectListItem>)ViewBag.Day, "Seçiniz", new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Hours, "", new { @class = "text-danger" })
                    <br /><br />*@
                    <button>Ekle</button>

                </div>
                }

            </div>

        </div>
    </div>
</div>

TrainingProje/Proje/ProjeMvc/Views/TrainingProgramDetail/Delete.cshtml
@model Entities.Concrete.TrainingProgramDetail

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html>


<br />
<head>
    <title>Home - AuthTake @*:: w3layouts*@</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/web/css/style.css" type="text/css" media="all" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="~/web/css/slider.css" rel="stylesheet" type="text/css" media="all" />
    <script src="~/web/js/jquery.min.js"></script>
    <script src="~/web/js/responsiveslides.min.js"></script>

    <script>
        // You can also use "$(window).load(function() {"
        $(function () {
            // Slideshow 1
            $("#slider1").responsiveSlides({
                auto: true,
                nav: true,
                speed: 500,
                namespace: "callbacks",
            });
        });
    </script>
</head>

<body>
    <h3>Eğitimi silmek istediğinize emin misiniz?</h3>

    <br />


    <div>
        <br />
        <br />
        <br />
        <br />
        <dl class="row">
            
            <dt class="col-sm-2">
                @Html.Label("Eğitim başlangıç tarihi:")
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.StartDate)
            </dd>
            <dt class="col-sm-2">
                @Html.Label("Eğitim son tarihi:")
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.EndDate)
            </dd>
            <dt class="col-sm-2">
                @Html.Label("Açıklama:")
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
        </dl>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        @*<hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.UserName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.UserName)
                </dd>
            </dl>*@

        <form asp-action="Delete">
            <input type="hidden" asp-for="TrainingProgramDetailId" />
            <input type="submit" value="Sil" class="btn btn-danger" />
            @*<a asp-action="Site/GetAll">Önceki Sayfa</a>*@
        </form>
        <br />
        <br />
        <a href="/Manager/GetAll" class="btn btn-success">Geri Dön</a>
    </div>
</body>
</html>
}

TrainingProje/Proje/ProjeMvc/Views/TrainingProgramDetail/GetAll.cshtml
@using Entities.Concrete
@model List<Training>

@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        @*<h2>Hoşgeldiniz @ViewBag.username</h2>*@
        <!-- Trigger the modal with a button -->
        <br />

        @if (TempData["AlertMessage"] != null)
        {
            <div class="alert alert-success">
                <strong>Mesajınız!</strong>@TempData["AlertMessage"]
                <button type="button" class="close" data-dismiss="alert">
                    <span>&times;</span>
                    @*<span>x</span>*@
                </button>
            </div>
        }

        <div class="p-5 w-100 m-0">
            <a href="/Educator/GetAll" class="btn btn-success">Geri Dön</a>

            <a href="/Manager/Logout" class="btn btn-success">Çıkış Yap</a>
        </div>
        
        <br />
        

        <table class="table table-bordered">
            <tr>
                @*<th><b>Eğitmenin Unvanı</b></th>*@
                
                <th><b>Eğitim başlangıç tarihi</b></th>
                <th><b>Eğitim son tarihi</b></th>
                <th><b>Son başvuru tarihi</b></th>
                <th><b>Eğitimin kontenjan sayısı</b></th>
                <th><b>Toplam Eğitim saati</b></th>
            </tr>
            
            @foreach (var item in Model)
            {
                <tr>
                    @*<td>@item.TitleName</td>*@
                    <td>@item.TrainingStartdate.ToString("dd.MM.yyyy")</td>
                    <td>@item.TrainingLastdate.ToString("dd.MM.yyyy")</td>
                    @*<td>@item.Trainingstartdate</td>
                        <td>@item.Traininglastdate</td>*@
                    <td>@item.Trainingdate.ToString("dd.MM.yyyy")</td>
                    @*<td>@item.Trainingdate</td>*@
                    <td>@item.kota</td>
                    <td>@item.TotalHours</td>


                    <td><a href="/TrainingProgram/Program?TrainingId=@item.TrainingId" class="btn btn-success">Programı Gör</a></td>
                    
                </tr>

            }
        </table>
    </div>

   

    <br />

</body>
</html>

TrainingProje/Proje/ProjeMvc/Views/TrainingProgramDetail/Show.cshtml
@{
    ViewData["Title"] = "Show";

}

@section Styles{
    <link href='fullcalendar/main.css' rel='stylesheet' />
    <link href="~/fullcalendar/lib/main.css" rel="stylesheet" />
    <link href='https://use.fontawesome.com/releases/v5.0.6/css/all.css' rel='stylesheet'>
    <link href="~/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/twitter-bootstrap/js/bootstrap.js"></script>
}

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Eğitim merkezi</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Yetkili Kişi</h6>
                    <p class="card-text">Eğitim planlama sistemine hoş geldiniz</p>
                    <a href="/Manager/Logout" class="card-link">Çıkış yap</a>
                </div>
            </div> 
            <br />
            <ul class="list-group">
                <li class="list-group-item"> Prof.Ali Kaya <button class = "btn btn-sm mt-2 pull-left" style = "background-color:red;"</button></li>
                <li class="list-group-item"> Eğitici Sevgi Gür <button class = "btn btn-sm mt-2 pull-right" style = "background-color:blueviolet;"</button></li>
            </ul>
        </div>
        <div class="col-md-9">
            @*<div class="container"> </div>*@
            <div id="calendar"></div>

        </div>
    </div>
</div>
    
    


    @section Scripts {

        <script src="~/fullcalendar/lib/main.js"></script>
        <script src="~/fullcalendar/lib/locales-all.js"></script>


        <script>

            document.addEventListener('DOMContentLoaded', function () {
                var calendarEl = document.getElementById('calendar');
                var calendar = new FullCalendar.Calendar(calendarEl, {

                    //themeSystem:'bootstrap',
                    //bootstrapFontAwesome: {
                    //    listWeek : 'fa-list',
                    //},
                    locale: "tr",
                    timeFormat: 'h(:mm)a',
                    headerToolbar: {
                        left: 'prev,next today,addEvent',
                        center: 'title',
                        right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
                    },
                    footerToolbar: {
                        left: 'prevYear',
                        right: 'nextYear'
                    },
                    //scrollTime :'08:00:00',
                    minTime: '08:00:00',
                    //slotDuration: '00:15:00',
                    //slotLabelInterval: '00:15:00',
                    slotLabelFormat: {
                        hour: '2-digit',
                        minute: '2-digit',
                        //    /*omitZeroMinute: true, saatleri tek gösterir*/
                    },
                    fixedWeekCount: true,
                    //handleWindowResize: true,
                    //windowResizeDelay: 1000,
                    //windowResize: function (view) {
                    //    alert('Takvim yeniden boyutlandırıldı.');
                    //},
                    contentHeight: 450,
                    defaultView: 'dayGridMonth',
                    weekends: true,/*hafta sonlarını getirmez*/

                    titleFormat: {
                        year: 'numeric',
                        month: 'long',
                        day: 'numeric'
                    },
                    titleRangeSeparator: '/',
                    columnHeaderFormat: {
                        weekday: 'long',
                    },
                    customButtons: {
                        addEvent: {
                            text: 'Ekle',
                            click: function () {

                            }
                        }
                    },
                    //views: {
                    //    timeGridFourDay: {
                    //        type: 'timeGrid',
                    //        dayCount: 4,
                    //        //duration: {days : 4},
                    //        buttonText : '4 Gün'
                    //    }
                    //}
                    //eventTimeformat: {
                    //    hour: '2-digit',
                    //    minute: '2-digit',
                    //    /*second: '',*/
                    //},
                    validRange: {//Bu tarihten öncesini gösterme
                        start: '2020-09-30'
                    },
                    eventOrder: 'title',//sıralı getir/çalışmadı
                    timeZone: 'UTC',
                    events: [
                        {
                            id: 'x',
                            title: 'Merhaba',
                            start: '2022-09-25T08:00:00.000Z',
                            end: '2022-09-25T10:30:00.000Z'
                        },
                        {
                            id: 'a',
                            title: 'Merhabaa',
                            start: '2022-09-25T13:10:00.000Z',
                            end: '2022-09-25T15:30:00.000Z'
                        }
                    ],
                    eventRender: function (info) {
                        console.log(info.event.title);//event,el,isMirror
                    },
                    selectable: true,
                    select: function (selectionInfo) {
                        console.log(selectionInfo);
                        //seçildiğinde çalışmasını istediğim kodlar
                    },
                    eventClick: function (info) {
                        alert(info.event.title);
                    },
                    //eventMouseEnter: function (onMouse) {
                    //    alert(onMouse.event.start);
                    //}
                    //eventMouseLeave: function (onleave) {
                    //    alert(onleave.event.start);
                    //}
                    /*timeFormat: 'H(:mm)'*/
                    editable: true, // edit yapabiliyorum hareket ettirebiliyorum yani
                    //eventStartEditale : false, // başlangıç zamanını deiştirilebilir olup olmadığına bakar
                    //eventDurationEditable: false//başlangıç ve bitiş zaman aralığı sabit ve ben onu değiştiremiyorum.
                    //eventOverlap: function (stillEvent, movingEvent) {//çakışmaları önlemek için
                    //    //süzgeç
                    //    return stillEvent.allDay && movingEvent.allDay;
                    //},
                    //eventConstraint: { //sadece bu iki saat arasında güncellemeye izin ver
                    //    startTime : '08:00',
                    //    endTime: '22:00',
                    //    daysOfWeek : [1,2,3] // bu üç güne güncelleme için izin verilmez
                    //},
                    //eventAllow: function (dropInfoEvet, draggedEvent) {
                    //    //kontrol--mesela başlangıç tarihi belirlenenden önce mi
                    //    console.log(dropInfoEvent.start);
                    //    return false;
                    //}

                });
                calendar.render();
                /*console.renderEvents();*/
            });

        </script>
    }
    <body>

    </body>

TrainingProje/Proje/ProjeMvc/Views/TrainingProgramDetail/dene.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Takvim</title>
    <link href="~/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <!--fullcalendar pluding-->
    <link href="~/fullcalendar/lib/main.css" rel="stylesheet" />
    <script src="~/fullcalendar/lib/main.js"></script>
    <script src="~/fullcalendar/lib/locales-all.js"></script>
    <link href='https://use.fontawesome.com/releases/v5.0.6/css/all.css' rel='stylesheet'>
    <script>

        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');

            var calendar = new FullCalendar.Calendar(calendarEl, {
                headerToolbar: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek,timeGridDay'
                },
                initialDate: '2022-12-19',
                locale: "tr",
                /*themeSystem: "bootstrap",*/
                navLinks: true, // can click day/week names to navigate views
                selectable: true,
                selectMirror: true,
                select: function (arg) {
                    var title = prompt('Event Title:' + arg.start);
                    if (title) {
                        calendar.addEvent({
                            title: title,
                            start: arg.start,
                            end: arg.end,
                            allDay: arg.allDay
                        })
                    }
                    calendar.unselect()
                },
                eventClick: function (arg) {
                    if (confirm('Bu etkinliği silmek istediğinizden emin misiniz?')) {
                        arg.event.remove()
                    }
                },
                editable: true,
                dayMaxEvents: true, // allow "more" link when too many events
                events: [
                    {
                        title: 'All Day Event',
                        start: '2020-09-01'
                    },
                    {
                        title: 'Long Event',
                        start: '2020-09-07',
                        end: '2020-09-10'
                    },
                    {
                        groupId: 999,
                        title: 'Repeating Event',
                        start: '2020-09-09T16:00:00'
                    },
                    {
                        groupId: 999,
                        title: 'Repeating Event',
                        start: '2020-09-16T16:00:00'
                    },
                    {
                        title: 'Conference',
                        start: '2020-09-11',
                        end: '2020-09-13'
                    },
                    {
                        title: 'Meeting',
                        start: '2020-09-12T10:30:00',
                        end: '2020-09-12T12:30:00'
                    },
                    {
                        title: 'Lunch',
                        start: '2020-09-12T12:00:00'
                    },
                    {
                        title: 'Meeting',
                        start: '2020-09-12T14:30:00'
                    },
                    {
                        title: 'Happy Hour',
                        start: '2020-09-12T17:30:00'
                    },
                    {
                        title: 'Dinner',
                        start: '2020-09-12T20:00:00'
                    },
                    {
                        title: 'Birthday Party',
                        start: '2022-09-13T07:00:00'
                    },
                    {
                        title: 'Click for Google',
                        url: 'http://google.com/',
                        start: '2022-09-28'
                    }
                ]
            });

            calendar.render();
        });

    </script>
</head>

<body>

    <div class="container">
        <div id='calendar'></div>
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-context">
                    <div class="model-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title"><span id="eventTitle"></span></h4>
                    </div>
                    <div class="modal-body">
                        <button id="btnDelete" class="btn btn-default btn-sm pull-right">
                            <span class="glyphicon glyphicon-remove"></span> SİL
                        </button>
                        <button id="btnEdit" class="btn btn-default btn-sm pull-right" style="margin-right:5px;">
                            <span class="glyphicon glyphicon-pencil"></span> DÜZENLE
                        </button>
                        <p id="pDetails"></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="~/twitter-bootstrap/js/bootstrap.js"></script>
</body>
</html>
   
              









@*//$('#myModal #eventTitle').text(arg.trainingname);
                    //var $discription = $('
<div />');
                    //$discription.append($('
<p />').html('<b>TrainingName</b>' + arg.trainingname));
                    //$('#myModal').modal();*@